---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

parameters:
  tests:
    build_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.build%>'
    img_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.img%>'
    test_packages_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.test_packages%>'
    test_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.tests%>'

builds:
  linux64_gecko:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_desktop_opt.yml
        post-tasks:
          tasks/tests/b2g_build_test.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_build_unit.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_gaia_js_integration_tests.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_linter.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_gaia_ui_test_accessibility.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_gaia_ui_test_functional.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_gaia_ui_test_unit.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_gaia_unit.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_gaia_unit.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_mochitest_oop.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_reftests_sanity_oop.yml:
            inherit-parameters:
              - tests
      debug:
        task: tasks/builds/b2g_desktop_debug.yml
          tasks/tests/b2g_gaia_ui_test_accessibility.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_gaia_ui_test_functional.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_gaia_ui_test_unit.yml:
            inherit-parameters:
              - tests
        post-tasks:
  linux64-mulet:
    platforms:
      - Mulet Linux
    types:
      opt:
        task: tasks/builds/mulet_linux.yml
        post-tasks:
          tasks/tests/mulet_build_test.yml:
            inherit-parameters:
              - tests
          tasks/tests/mulet_build_unit.yml:
            inherit-parameters:
              - tests
          tasks/tests/mulet_gaia_js_integration_tests.yml:
            inherit-parameters:
              - tests
          tasks/tests/mulet_linter.yml:
            inherit-parameters:
              - tests
          tasks/tests/mulet_mochitests.yml:
            inherit-parameters:
              - tests
          tasks/tests/mulet_reftests.yml:
            inherit-parameters:
              - tests
  emulator-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_kk_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_kk_debug.yml
  emulator-l:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_l_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_l_debug.yml
  emulator-jb:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_jb_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_jb_debug.yml
  emulator:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_ics_opt.yml
        post-tasks:
          tasks/tests/b2g_emulator_cpp_unit.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_emulator_crashtest.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_emulator_marionette.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_emulator_marionette_webapi.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_emulator_mochitest.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_emulator_reftest.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_emulator_xpcshell_chunked.yml:
            inherit-parameters:
              - tests
      debug:
        task: tasks/builds/b2g_emulator_ics_debug.yml
        post-tasks:
          tasks/tests/b2g_emulator_cpp_unit.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_emulator_mochitest.yml:
            inherit-parameters:
              - tests
          tasks/tests/b2g_emulator_xpcshell_chunked.yml:
            inherit-parameters:
              - tests
  aries:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_opt.yml
      debug:
        task: tasks/builds/b2g_aries_spark_debug.yml
  aries-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_eng.yml
  flame-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_opt.yml
      debug:
        task: tasks/builds/b2g_flame_kk_debug.yml
  flame-kk-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_eng.yml
        post-tasks:
          tasks/tests/flame_kk_gaia_ui_test_functional.yml:
            inherit-parameters:
              - tests
          tasks/tests/flame_kk_gaia_ui_test_functional_dsds.yml:
            inherit-parameters:
              - tests
          tasks/tests/flame_kk_gaia_ui_test_sanity.yml:
            inherit-parameters:
              - tests
          tasks/tests/flame_kk_gaia_ui_test_unit.yml:
            inherit-parameters:
              - tests
  flame-kk-spark-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_spark_eng.yml

