---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

parameters:
  tests:
    build_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.build%>'
    img_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.img%>'
    test_packages_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.test_packages%>'
    test_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.tests%>'

builds:
  linux64_gecko:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_desktop_opt.yml
        post-tasks:
          gaia-build:
            task: tasks/tests/b2g_build_test.yml
            inherit-parameters:
              - tests
          gaia-build-unit:
            task: tasks/tests/b2g_build_unit.yml
            inherit-parameters:
              - tests
          gaia-js-integration:
            task: tasks/tests/b2g_gaia_js_integration_tests.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 4
          gaia-linter:
            task: tasks/tests/b2g_linter.yml
            inherit-parameters:
              - tests
          gaia-unit:
            task: tasks/tests/b2g_gaia_unit.yml
            inherit-parameters:
              - tests
          gaia-ui-test-accessibility:
            task: tasks/tests/b2g_gaia_ui_test_accessibility.yml
            inherit-parameters:
              - tests
          gaia-ui-test-functional:
            task: tasks/tests/b2g_gaia_ui_test_functional.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 3
          gaia-ui-test-unit:
            task: tasks/tests/b2g_gaia_ui_test_unit.yml
            inherit-parameters:
              - tests
          gaia-ui-test-oop:
            task: tasks/tests/b2g_gip_oop.yml
            inherit-parameters:
              - tests
          mochitest-oop:
            task: tasks/tests/b2g_mochitest_oop.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 1
          reftest:
            task: tasks/tests/b2g_reftests.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 10
          reftest-sanity-oop:
            task: tasks/tests/b2g_reftests_sanity_oop.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 1
          xpcshell:
            task: tasks/tests/b2g_emulator_xpcshell_chunked.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 2
      debug:
        task: tasks/builds/b2g_desktop_debug.yml
        post-tasks:
          gaia-js-integration:
            task: tasks/tests/b2g_gaia_js_integration_tests.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 4
  linux64-mulet:
    platforms:
      - Mulet Linux
    types:
      opt:
        task: tasks/builds/mulet_linux.yml
        post-tasks:
          mochitest:
            task: tasks/tests/mulet_mochitests.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 5
          reftest:
            task: tasks/tests/mulet_reftests.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 6
  emulator-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_kk_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_kk_debug.yml
  emulator-jb:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_jb_opt.yml
        post-tasks:
          mochitest:
            task: tasks/tests/b2g_emulator_mochitest.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 1
      debug:
        task: tasks/builds/b2g_emulator_jb_debug.yml
  emulator:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_ics_opt.yml
        post-tasks:
          cppunit:
            task: tasks/tests/b2g_emulator_cpp_unit.yml
            inherit-parameters:
              - tests
          crashtest:
            task: tasks/tests/b2g_emulator_crashtest.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 3
          jsreftest:
            task: tasks/tests/b2g_emulator_js_reftest.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 3
          marionette:
            task: tasks/tests/b2g_emulator_marionette.yml
            inherit-parameters:
              - tests
          marionette-webapi:
            task: tasks/tests/b2g_emulator_marionette_webapi.yml
            inherit-parameters:
              - tests
          mochitest:
            task: tasks/tests/b2g_emulator_mochitest.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 9
          mochitest-media:
            task: tasks/tests/b2g_emulator_mochitest_media.yml
            inherit-parameters:
              - tests
          reftest:
            task: tasks/tests/b2g_emulator_reftest.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 20
          xpcshell:
            task: tasks/tests/b2g_emulator_xpcshell.yml
            inherit-parameters:
              - tests
      debug:
        task: tasks/builds/b2g_emulator_ics_debug.yml
        post-tasks:
          cppunit:
            task: tasks/tests/b2g_emulator_cpp_unit.yml
            inherit-parameters:
              - tests
          crashtest:
            task: tasks/tests/b2g_emulator_crashtest.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 3
          marionette:
            task: tasks/tests/b2g_emulator_marionette.yml
            inherit-parameters:
              - tests
          marionette-webapi:
            task: tasks/tests/b2g_emulator_marionette_webapi.yml
            inherit-parameters:
              - tests
          mochitest:
            task: tasks/tests/b2g_emulator_mochitest.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 20
          reftest:
            task: tasks/tests/b2g_emulator_reftest.yml
            inherit-parameters:
              - tests
            parameters:
              total_chunks: 10

