---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

parameters:
  tests:
    build_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.build%>'
    img_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.img%>'
    test_packages_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.test_packages%>'
    test_url: 'https://queue.taskcluster.net/v1/task/<%build_slugid%>/artifacts/<%root.task.extra.locations.tests%>'

builds:
  linux64_gecko:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_desktop_opt.yml
        post-tasks:
          gaia-build:
            task: tasks/tests/b2g_build_test.yml
            inherit-parameters:
              - tests
          gaia-build-unit:
            task: tasks/tests/b2g_build_unit.yml
            inherit-parameters:
              - tests
          gaia-js-integration:
            task: tasks/tests/b2g_gaia_js_integration_tests.yml
            inherit-parameters:
              - tests
          gaia-linter:
            tasks/tests/b2g_linter.yml:
            inherit-parameters:
              - tests
          gaia-ui-test-accessibility:
            task: tasks/tests/b2g_gaia_ui_test_accessibility.yml
            inherit-parameters:
              - tests
          gaia-ui-test-functional:
            task: tasks/tests/b2g_gaia_ui_test_functional.yml
            inherit-parameters:
              - tests
          gaia-ui-test-unit:
            task: tasks/tests/b2g_gaia_ui_test_unit.yml
            inherit-parameters:
              - tests
          gaia-unit:
            task: tasks/tests/b2g_gaia_unit.yml
            inherit-parameters:
              - tests
          mochitest-oop:
            task: tasks/tests/b2g_mochitest_oop.yml
            inherit-parameters:
              - tests
          reftest-sanity-oop:
            task: tasks/tests/b2g_reftests_sanity_oop.yml
            inherit-parameters:
              - tests
      debug:
        task: tasks/builds/b2g_desktop_debug.yml
        post-tasks:
          gaia-ui-test-accessibility:
            task: tasks/tests/b2g_gaia_ui_test_accessibility.yml
            inherit-parameters:
              - tests
          gaia-ui-test-functional:
            task: tasks/tests/b2g_gaia_ui_test_functional.yml
            inherit-parameters:
              - tests
          gaia-ui-test-unit:
            task: tasks/tests/b2g_gaia_ui_test_unit.yml
            inherit-parameters:
              - tests
  linux64-mulet:
    platforms:
      - Mulet Linux
    types:
      opt:
        task: tasks/builds/mulet_linux.yml
        post-tasks:
          gaia-build:
            task: tasks/tests/mulet_build_test.yml
            inherit-parameters:
              - tests
          gaia-build-unit:
            task: tasks/tests/mulet_build_unit.yml
            inherit-parameters:
              - tests
          gaia-js-integration:
            task: tasks/tests/mulet_gaia_js_integration_tests.yml
            inherit-parameters:
              - tests
          gaia-linter:
            task: tasks/tests/mulet_linter.yml
            inherit-parameters:
              - tests
          mochitest:
            task: tasks/tests/mulet_mochitests.yml
            inherit-parameters:
              - tests
          reftest:
            task: tasks/tests/mulet_reftests.yml
            inherit-parameters:
              - tests
  emulator-l:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_l_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_l_debug.yml
  emulator-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_kk_opt.yml
        post-tasks:
          marionette:
            task: tasks/tests/b2g_emulator_marionette.yml
            inherit-parameters:
              - tests
          mochitest:
            task: tasks/tests/b2g_emulator_mochitest.yml
            inherit-parameters:
              - tests
          marionette-webapi:
            task: tasks/tests/b2g_emulator_marionette_webapi.yml
            inherit-parameters:
              - tests
          reftest:
            task: tasks/tests/b2g_emulator_reftest.yml
            inherit-parameters:
              - tests
          xpcshell:
            task: tasks/tests/b2g_emulator_xpcshell_chunked.yml
            inherit-parameters:
              - tests
      debug:
        task: tasks/builds/b2g_emulator_kk_debug.yml
        post-tasks:
          mochitest:
            task: tasks/tests/b2g_emulator_mochitest.yml
            inherit-parameters:
              - tests
  emulator-x86-l:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_x86_l_opt.yml
        post-tasks:
          mochitest:
            task: tasks/tests/b2g_emulator_mochitest.yml
            inherit-parameters:
              - tests
          reftest:
            task: tasks/tests/b2g_emulator_reftest.yml
            inherit-parameters:
              - tests
          xpcshell:
            task: tasks/tests/b2g_emulator_xpcshell_chunked.yml
            inherit-parameters:
              - tests
  emulator-x86-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_x86_kk_opt.yml
        post-tasks:
          mochitest:
            task: tasks/tests/b2g_emulator_mochitest.yml
            inherit-parameters:
              - tests
  emulator-jb:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_jb_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_jb_debug.yml
  emulator:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_ics_opt.yml
        post-tasks:
          cppunit:
            task: tasks/tests/b2g_emulator_cpp_unit.yml
            inherit-parameters:
              - tests
          crashtest:
            task: tasks/tests/b2g_emulator_crashtest.yml
            inherit-parameters:
              - tests
          marionette:
            task: tasks/tests/b2g_emulator_marionette.yml
            inherit-parameters:
              - tests
          marionette-webapi:
            task: tasks/tests/b2g_emulator_marionette_webapi.yml
            inherit-parameters:
              - tests
          mochitest:
            task: tasks/tests/b2g_emulator_mochitest.yml
            inherit-parameters:
              - tests
          reftest:
            task: tasks/tests/b2g_emulator_reftest.yml
            inherit-parameters:
              - tests
          xpcshell:
            task: tasks/tests/b2g_emulator_xpcshell_chunked.yml
            inherit-parameters:
              - tests
      debug:
        task: tasks/builds/b2g_emulator_ics_debug.yml
        post-tasks:
          cppunit:
            task: tasks/tests/b2g_emulator_cpp_unit.yml
            inherit-parameters:
              - tests
          mochitest:
            task: tasks/tests/b2g_emulator_mochitest.yml
            inherit-parameters:
              - tests
          xpcshell:
            task: tasks/tests/b2g_emulator_xpcshell_chunked.yml
            inherit-parameters:
              - tests
  aries:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_opt.yml
      debug:
        task: tasks/builds/b2g_aries_spark_debug.yml
  aries-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_eng.yml
  flame-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_opt.yml
      debug:
        task: tasks/builds/b2g_flame_kk_debug.yml
  flame-kk-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_eng.yml
  dolphin:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_dolphin_opt.yml
  dolphin-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_dolphin_eng.yml
  dolphin-512:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_dolphin_512_opt.yml
  dolphin-512-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_dolphin_512_eng.yml
  android-api-11:
    platforms:
      - Android
    types:
      opt:
        task: tasks/builds/android_api_11.yml
        post-tasks:
          upload-symbols:
            task: tasks/post-builds/upload_symbols.yml
  linux64:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/opt_linux64.yml
        post-tasks:
          upload-symbols:
            task: tasks/post-builds/upload_symbols.yml
      debug:
        task: tasks/builds/dbg_linux64.yml
        post-tasks:
          upload-symbols:
            task: tasks/post-builds/upload_symbols.yml
  sm-plain:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_plain.yml
      debug:
       task: tasks/builds/sm_plaindebug.yml
  sm-arm-sim:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_arm_sim.yml
  sm-arm-sim-osx:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_arm_sim_osx.yml
  sm-compacting:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_compacting.yml
  sm-generational:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_generational.yml
  sm-rootanalysis:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_rootanalysis.yml
  sm-warnaserr:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_warnaserr.yml
      debug:
        task: tasks/builds/sm_warnaserrdebug.yml

